/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import org.junit.jupiter.api.Test;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
